workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Create Podfile if not exists
        script: |
          if [ ! -f "ios/Podfile" ]; then
            echo "platform :ios, '12.0'" > ios/Podfile
            echo "use_frameworks!" >> ios/Podfile
            echo "target 'Runner' do" >> ios/Podfile
            echo "  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))" >> ios/Podfile
            echo "end" >> ios/Podfile
          fi
      - name: Install iOS pods
        script: |
          cd ios
          pod install --repo-update
      - name: Build iOS
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - belal24@gmail.com