workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.yourcompany.twonet"  # غيّر هذا لـ Bundle ID الخاص بك
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install iOS pods
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com