workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
      - name: Get packages
        script: flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
      - name: Build iOS
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - belal24@gmail.com