// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRSnq4foM1s4oc7-J1X7-q2J264Xxe_gU',
    appId: '1:463551205492:web:1a28e3c3a92116434ac121',
    messagingSenderId: '463551205492',
    projectId: 'net-33d75',
    authDomain: 'net-33d75.firebaseapp.com',
    storageBucket: 'net-33d75.firebasestorage.app',
    measurementId: 'G-J1XKT1NSTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3_X5J3cwSV-mCIT8DvnYCJbAyR3NL4C8',
    appId: '1:463551205492:android:5d642f0bc3bc52724ac121',
    messagingSenderId: '463551205492',
    projectId: 'net-33d75',
    storageBucket: 'net-33d75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzdeBBAvKAuOn3iGP45SoMRZdj7G0YcR8',
    appId: '1:463551205492:ios:c02eb3c6fe5aa5914ac121',
    messagingSenderId: '463551205492',
    projectId: 'net-33d75',
    storageBucket: 'net-33d75.firebasestorage.app',
    iosBundleId: 'com.example.twonetCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzdeBBAvKAuOn3iGP45SoMRZdj7G0YcR8',
    appId: '1:463551205492:ios:c02eb3c6fe5aa5914ac121',
    messagingSenderId: '463551205492',
    projectId: 'net-33d75',
    storageBucket: 'net-33d75.firebasestorage.app',
    iosBundleId: 'com.example.twonetCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRSnq4foM1s4oc7-J1X7-q2J264Xxe_gU',
    appId: '1:463551205492:web:f4ae713ae3041ef94ac121',
    messagingSenderId: '463551205492',
    projectId: 'net-33d75',
    authDomain: 'net-33d75.firebaseapp.com',
    storageBucket: 'net-33d75.firebasestorage.app',
    measurementId: 'G-V6GLS5QPL0',
  );
}
